[pytest]
DJANGO_SETTINGS_MODULE = config.settings.development

python_files = tests.py test_*.py *_tests.py
python_classes = Test*
python_functions = test_*

addopts =
    -v
    --reuse-db
    --tb=short
    --strict-markers
    --cov=apps
    --cov-report=term-missing
    --cov-report=html

testpaths = apps

markers =
    unit: tests unitarios rapidos
    integration: tests de integracion
    slow: tests lentos