# Generated by Django 5.1.15 on 2026-05-09 21:34

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Estancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "fecha_checkin",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fecha_checkout", models.DateTimeField(blank=True, null=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("EN_CURSO", "En curso"),
                            ("FINALIZADA", "Finalizada"),
                        ],
                        default="EN_CURSO",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Estancia",
                "verbose_name_plural": "Estancias",
                "db_table": "estancia",
                "ordering": ["-fecha_checkin"],
            },
        ),
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "numero",
                    models.CharField(help_text='Ej: "101", "PH-1"', max_length=10),
                ),
                ("piso", models.PositiveSmallIntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("DISPONIBLE", "Disponible"),
                            ("OCUPADA", "Ocupada"),
                            ("LIMPIEZA", "En limpieza"),
                            ("MANTENIMIENTO", "Mantenimiento"),
                        ],
                        default="DISPONIBLE",
                        max_length=15,
                    ),
                ),
                (
                    "activa",
                    models.BooleanField(
                        default=True,
                        help_text="Si esta en False, no aparece en busquedas de disponibilidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Habitacion",
                "verbose_name_plural": "Habitaciones",
                "db_table": "habitacion",
                "ordering": ["hotel", "piso", "numero"],
            },
        ),
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=150)),
                (
                    "ruc",
                    models.CharField(
                        help_text="RUC peruano de 11 digitos",
                        max_length=11,
                        unique=True,
                    ),
                ),
                ("direccion", models.CharField(max_length=255)),
                (
                    "estrellas",
                    models.PositiveSmallIntegerField(
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Hotel",
                "verbose_name_plural": "Hoteles",
                "db_table": "hotel",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Folio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "igv",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[("ABIERTO", "Abierto"), ("CERRADO", "Cerrado")],
                        default="ABIERTO",
                        max_length=10,
                    ),
                ),
                ("fecha_cierre", models.DateTimeField(blank=True, null=True)),
                (
                    "estancia",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="folio",
                        to="hoteleria.estancia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Folio",
                "verbose_name_plural": "Folios",
                "db_table": "folio",
            },
        ),
        migrations.AddField(
            model_name="estancia",
            name="habitacion",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estancias",
                to="hoteleria.habitacion",
            ),
        ),
        migrations.AddField(
            model_name="habitacion",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="habitaciones",
                to="hoteleria.hotel",
            ),
        ),
        migrations.CreateModel(
            name="Huesped",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "tipo_doc",
                    models.CharField(
                        choices=[
                            ("DNI", "DNI"),
                            ("CE", "Carne de extranjeria"),
                            ("PAS", "Pasaporte"),
                        ],
                        max_length=4,
                    ),
                ),
                ("num_doc", models.CharField(max_length=20)),
                ("nombres", models.CharField(max_length=120)),
                ("apellidos", models.CharField(max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telefono", models.CharField(blank=True, max_length=20)),
                ("nacionalidad", models.CharField(default="Peruana", max_length=60)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Huesped",
                "verbose_name_plural": "Huespedes",
                "db_table": "huesped",
                "ordering": ["apellidos", "nombres"],
                "indexes": [
                    models.Index(fields=["num_doc"], name="idx_huesped_num_doc"),
                    models.Index(fields=["apellidos"], name="idx_huesped_apellidos"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tipo_doc", "num_doc"), name="uq_huesped_documento"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reserva",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("fecha_entrada", models.DateField()),
                ("fecha_salida", models.DateField()),
                ("num_adultos", models.PositiveSmallIntegerField(default=1)),
                ("num_ninos", models.PositiveSmallIntegerField(default=0)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("PENDIENTE", "Pendiente"),
                            ("CONFIRMADA", "Confirmada"),
                            ("CHECKIN", "Check-in realizado"),
                            ("CHECKOUT", "Check-out realizado"),
                            ("CANCELADA", "Cancelada"),
                            ("NO_SHOW", "No show"),
                        ],
                        default="PENDIENTE",
                        max_length=15,
                    ),
                ),
                (
                    "origen",
                    models.CharField(
                        choices=[
                            ("WEB", "Web directa"),
                            ("TELEFONO", "Telefono"),
                            ("WALKIN", "Walk-in"),
                            ("OTA", "OTA (Booking, Expedia)"),
                        ],
                        default="WEB",
                        max_length=10,
                    ),
                ),
                (
                    "precio_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculado automaticamente sumando tarifas dia a dia",
                        max_digits=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "creada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservas_creadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="hoteleria.habitacion",
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="hoteleria.hotel",
                    ),
                ),
                (
                    "huesped",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservas",
                        to="hoteleria.huesped",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserva",
                "verbose_name_plural": "Reservas",
                "db_table": "reserva",
                "ordering": ["-fecha_entrada"],
            },
        ),
        migrations.AddField(
            model_name="estancia",
            name="reserva",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="estancia",
                to="hoteleria.reserva",
            ),
        ),
        migrations.CreateModel(
            name="TipoHabitacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("nombre", models.CharField(max_length=80)),
                (
                    "capacidad",
                    models.PositiveSmallIntegerField(
                        help_text="Numero maximo de huespedes"
                    ),
                ),
                (
                    "precio_base",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Precio base por noche en S/. Se sobrescribe con Tarifa por temporada.",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "amenidades",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Ej: {"wifi": true, "minibar": false, "tv": true}',
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tipos_habitacion",
                        to="hoteleria.hotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de habitacion",
                "verbose_name_plural": "Tipos de habitacion",
                "db_table": "tipo_habitacion",
            },
        ),
        migrations.CreateModel(
            name="Tarifa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text='Ej: "Temporada Alta Verano 2026"', max_length=100
                    ),
                ),
                (
                    "precio_noche",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("activa", models.BooleanField(default=True)),
                (
                    "tipo_habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tarifas",
                        to="hoteleria.tipohabitacion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tarifa",
                "verbose_name_plural": "Tarifas",
                "db_table": "tarifa",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.AddField(
            model_name="habitacion",
            name="tipo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="habitaciones",
                to="hoteleria.tipohabitacion",
            ),
        ),
        migrations.CreateModel(
            name="CargoEstancia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                ("concepto", models.CharField(max_length=200)),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HABITACION", "Habitacion"),
                            ("RESTAURANTE", "Restaurante"),
                            ("LAVANDERIA", "Lavanderia"),
                            ("MINIBAR", "Minibar"),
                            ("SPA", "Spa"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=15,
                    ),
                ),
                ("fecha", models.DateTimeField(default=django.utils.timezone.now)),
                ("pagado", models.BooleanField(default=False)),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "estancia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cargos",
                        to="hoteleria.estancia",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo de estancia",
                "verbose_name_plural": "Cargos de estancia",
                "db_table": "cargo_estancia",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["estancia", "tipo"], name="idx_cargo_estancia_tipo"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("monto__gt", 0)),
                        name="ck_cargo_monto_positivo",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["habitacion", "fecha_entrada", "fecha_salida"],
                name="idx_reserva_solapamiento",
            ),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(fields=["estado"], name="idx_reserva_estado"),
        ),
        migrations.AddIndex(
            model_name="reserva",
            index=models.Index(
                fields=["fecha_entrada"], name="idx_reserva_fecha_entrada"
            ),
        ),
        migrations.AddConstraint(
            model_name="reserva",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_salida__gt", models.F("fecha_entrada"))),
                name="ck_reserva_salida_mayor_entrada",
            ),
        ),
        migrations.AddConstraint(
            model_name="reserva",
            constraint=models.CheckConstraint(
                condition=models.Q(("num_adultos__gte", 1)),
                name="ck_reserva_min_un_adulto",
            ),
        ),
        migrations.AddConstraint(
            model_name="reserva",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_total__gte", 0)),
                name="ck_reserva_precio_no_negativo",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipohabitacion",
            constraint=models.UniqueConstraint(
                fields=("hotel", "nombre"), name="uq_tipo_habitacion_por_hotel"
            ),
        ),
        migrations.AddConstraint(
            model_name="tipohabitacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_base__gt", 0)),
                name="ck_tipo_precio_base_positivo",
            ),
        ),
        migrations.AddConstraint(
            model_name="tipohabitacion",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacidad__gte", 1)),
                name="ck_tipo_capacidad_minima",
            ),
        ),
        migrations.AddIndex(
            model_name="tarifa",
            index=models.Index(
                fields=["tipo_habitacion", "fecha_inicio", "fecha_fin"],
                name="idx_tarifa_busqueda",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(("fecha_fin__gte", models.F("fecha_inicio"))),
                name="ck_tarifa_rango_valido",
            ),
        ),
        migrations.AddConstraint(
            model_name="tarifa",
            constraint=models.CheckConstraint(
                condition=models.Q(("precio_noche__gt", 0)),
                name="ck_tarifa_precio_positivo",
            ),
        ),
        migrations.AddIndex(
            model_name="habitacion",
            index=models.Index(fields=["estado"], name="idx_habitacion_estado"),
        ),
        migrations.AddIndex(
            model_name="habitacion",
            index=models.Index(
                fields=["hotel", "estado"], name="idx_habitacion_hotel_estado"
            ),
        ),
        migrations.AddConstraint(
            model_name="habitacion",
            constraint=models.UniqueConstraint(
                fields=("hotel", "numero"), name="uq_habitacion_numero_por_hotel"
            ),
        ),
    ]
