# Generated by Django 5.1.15 on 2026-05-15 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoteleria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cargoestancia",
            name="fecha_pago",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de pago"
            ),
        ),
        migrations.AddField(
            model_name="cargoestancia",
            name="metodo_pago",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EFECTIVO", "Efectivo"),
                    ("TARJETA", "Tarjeta"),
                    ("TRANSFERENCIA", "Transferencia"),
                    ("YAPE", "Yape"),
                    ("PLIN", "Plin"),
                ],
                max_length=20,
                null=True,
                verbose_name="Método de pago",
            ),
        ),
    ]
