# Generated by Django 5.1.15 on 2026-05-19 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hoteleria", "0002_cargoestancia_fecha_pago_cargoestancia_metodo_pago"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incidente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DESPERFECTO", "Desperfecto"),
                            ("CONSUMO_MINIBAR", "Consumo de minibar"),
                            ("ITEM_FALTANTE", "Item faltante"),
                            ("OTRO", "Otro"),
                        ],
                        default="OTRO",
                        max_length=20,
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        help_text="Detalle del incidente: que se encontro y donde"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("REPORTADO", "Reportado"),
                            ("EN_PROCESO", "En proceso"),
                            ("RESUELTO", "Resuelto"),
                        ],
                        default="REPORTADO",
                        max_length=15,
                    ),
                ),
                (
                    "habitacion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incidentes",
                        to="hoteleria.habitacion",
                    ),
                ),
                (
                    "reportado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incidentes_reportados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Incidente",
                "verbose_name_plural": "Incidentes",
                "db_table": "incidente",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["estado", "-created_at"], name="idx_incidente_estado"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LogAuditoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Actualizado en"),
                ),
                (
                    "accion",
                    models.CharField(
                        choices=[
                            ("LOGIN", "Inicio de sesion"),
                            ("LOGOUT", "Cierre de sesion"),
                            ("RESERVA_CREADA", "Reserva creada"),
                            ("RESERVA_CANCELADA", "Reserva cancelada"),
                            ("CHECKIN", "Check-in realizado"),
                            ("CHECKOUT", "Check-out realizado"),
                            ("CARGO_AGREGADO", "Cargo agregado"),
                            ("PAGO_REGISTRADO", "Pago registrado"),
                            ("DESCUENTO_APLICADO", "Descuento aplicado"),
                            ("USUARIO_CREADO", "Usuario creado"),
                            ("INCIDENTE_REPORTADO", "Incidente reportado"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "detalles",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Contexto: ids, antes/despues, monto, etc.",
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acciones_auditadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log de auditoria",
                "verbose_name_plural": "Logs de auditoria",
                "db_table": "log_auditoria",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["accion", "-created_at"], name="idx_log_accion"
                    ),
                    models.Index(
                        fields=["usuario", "-created_at"], name="idx_log_usuario"
                    ),
                ],
            },
        ),
    ]
