# Generated by Django 5.1.15 on 2026-05-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="rol",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("RECEPCIONISTA", "Recepcionista"),
                    ("HOUSEKEEPING", "Housekeeping"),
                ],
                default="RECEPCIONISTA",
                help_text="Rol del usuario en el sistema",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="telefono",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
